### ISSUE TITLE
Treba li .ba imati ovaj source?

### ISSUE THREAD

**Issue by antesto2** [wssto2/rv-dacia-header-footer-cg-bih-new-main#5]
@jzlimen jel se sjecas mozda treba li dacia.ba imati ovaj source ili smo presli za sve na  https://github.com/wssto2/dacia-header-footer-2022 

Zašto pitam, jer kad pogledam css unutar rabljenavozila.dacia.ba prikazuje mi css koji nije ni odavde ni s ovog linka nego neki treci (dok ova oba imaju identican css), pa sad mi nije jasno odakle povlacimo taj source?

**Comment by jzlimen** [comment]
Koliko vidim u kodu ovaj se koristi

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/16623112/217809679-5b973d18-8752-453e-80d7-0fb3e0243265.png">
<img width="972" alt="image" src="https://user-images.githubusercontent.com/16623112/217809788-460c2a4c-1d4f-4531-bf52-3ce01b327881.png">

**Comment by antesto2** [comment]
vjv sam ja nesto krivo gledo, sorry

Jel mozes sad molim te compileat novi kod? slucajno sam odma uploado na master branch

**Comment by jzlimen** [comment]
Riješeno
